### ISSUE TITLE
Python 2.7 compatibility

### ISSUE THREAD

**Issue by dimensi0n** [kdeal/devdocs-cli#1]
Does it work with python 2.7?

**Comment by kdeal** [comment]
Currently it only supports python 3, but that is because I didn't keep python 2.7 compatible in mind. I will update it to be python2.7 compatible.

**Comment by FatBoyXPC** [comment]
It appears that PyPi is still on `0.0.1`, which doesn't include these changes.

**Comment by kdeal** [comment]
I uploaded 0.0.2, which includes these changes.
